Repository openimsdk/chat, pull requests merged in 2023-12, with the labels that each got.

#289 feat: add openim chat fix support v3.5 install
  .github/workflows/scripts-test.yml
  Dockerfile
  Makefile
  README.md
  config/config.yaml.template
Labels: size/L

#303 feat: add some api about admin
  .github/workflows/scripts-test.yml
  internal/api/admin.go
  internal/api/router.go
  internal/rpc/admin/admin.go
  internal/rpc/chat/user.go
  pkg/common/constant/constant.go
  pkg/common/db/database/admin.go
  pkg/common/db/model/admin/admin.go
  pkg/common/db/table/admin/admin.go
  pkg/proto/admin/admin.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/chat/chat.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/XL

#306 feat: add openim chat env and config
  .gitignore
  cmd/api/admin-api/main.go
  config/config.yaml.template
  pkg/common/config/config.go
  scripts/docker_start_all.sh
Labels: size/L

#314 fix: Image Dockerfile Update Dockerfile
  Dockerfile
Labels: size/XS

#316 Update docker_start_all.sh
  scripts/docker_start_all.sh
Labels: size/XS

#272 Update README.md
  README.md
Labels: size/XS

#318 fix: fix the env in config
  deployments/templates/config.yaml
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/db/cache/init_redis.go
Labels: size/L

#301 Fix email related functions
  .github/workflows/scripts-test.yml
  internal/rpc/chat/login.go
  internal/rpc/chat/password.go
  pkg/proto/chat/chat.go
Labels: size/M

#321 openim create and fix scripts add config
  .github/workflows/scripts-test.yml
  config/Readme.md
  deployments/templates/config.yaml
  scripts/docker_start_all.sh
Labels: size/S

#323 fix: add component config env
  deployments/templates/config.yaml
  pkg/common/config/parse.go
Labels: size/M

#315 fix macOs cpu_count
  .github/workflows/scripts-test.yml
  scripts/build_all_service.sh
  scripts/stop_all.sh
Labels: size/M

#325 Update build-docker-image.yml
  .github/workflows/build-docker-image.yml
Labels: size/XS

#328 fix: fix the zk don't start problem
  pkg/common/config/parse.go
Labels: size/S

#329 Fix openim chat addr and port eque
  deployments/templates/config.yaml
  pkg/common/config/version
  tools/component/component.go
Labels: size/M

#331 fix: del the chan admin password encryption
  deployments/templates/config.yaml
  internal/rpc/admin/admin.go
Labels: size/XS

#332 Update config.yaml
  deployments/templates/config.yaml
Labels: size/XS

#335 update init config
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  pkg/common/apicall/call.go
  pkg/common/config/parse.go
  pkg/common/db/cache/init_redis.go
  pkg/discovery_register/k8s_discovery_register.go
  tools/component/component.go
Labels: size/L

#338 feat: Chat supports batch import of JSON and XLSX
  deployments/helm-charts/config.yaml
  deployments/templates/config.yaml
  go.mod
  go.sum
  internal/api/admin.go
  internal/api/mw.go
  internal/api/router.go
  pkg/common/config/config.go
  pkg/common/config/template.xlsx
  pkg/common/xlsx/main.go
  pkg/common/xlsx/model/user.go
  pkg/common/xlsx/sheet.go
  pkg/common/xlsx/utils.go
  pkg/proto/chat/chat.go
Labels: size/XL

#342 modify component check
  tools/component/component.go
Labels: size/XS

#343 fix component check
  tools/component/component.go
Labels: size/S

#344 update component check
  tools/component/component.go
Labels: size/XS

#345 update component check
  tools/component/component.go
Labels: size/S

#349 fix go mod
  go.mod
  go.sum
Labels: size/XS

#347 feat: add notification config
  deployments/templates/config.yaml
  internal/api/router.go
  internal/rpc/admin/admin.go
  pkg/common/chatrpcstart/start.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/db/model/admin/admin.go
  pkg/common/db/table/admin/admin.go
Labels: size/M

#353 Update scripts-test.yml
  .github/workflows/scripts-test.yml
Labels: size/XS
