Repository openimsdk/chat, pull requests merged in 2023-11, with the labels that each got.

#230 feat: Support email registration
  cmd/api/chat-api/main.go
  config/config.yaml
  go.mod
  go.sum
  internal/rpc/admin/admin.go
  internal/rpc/chat/chat.go
  internal/rpc/chat/login.go
  pkg/common/config/config.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/db/table/chat/attribute.go
  pkg/email/mail.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/L

#254 feat: add send email test
  pkg/email/mail.go
  pkg/email/mail_test.go
Labels: size/M

#260 fix: fix the flag parse
  pkg/common/config/parse.go
  pkg/common/constant/constant.go
Labels: size/M

#262 Update scripts-test.yml
  .github/workflows/scripts-test.yml
Labels: size/XS

#263 feat: openim-chat super docker images aliyun and docker hub
  .github/workflows/docker-buildx.yml
Labels: size/M

#237 feat: add supported architechture
  scripts/path_info.sh
Labels: size/XS

#274 fix: default verifyCode type and admin register user
  config/config.yaml
  internal/api/mw.go
  internal/api/router.go
  internal/rpc/chat/login.go
  pkg/common/mw/gin_log.go
  pkg/proto/chat/chat.go
Labels: size/M
