Repository openimsdk/chat, pull requests merged in 2023-07, with the labels that each got.

#10 modify searchFullUserInfo api
  internal/rpc/chat/user.go
  pkg/common/constant/constant.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/db/table/chat/attribute.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/M

#21 add parameter check
  pkg/proto/admin/admin.go
  pkg/proto/chat/chat.go
Labels: size/L

#28 reconstruct some rpc
  .github/workflows/chatci.yml
  .goreleaser.yaml
  config/config.yaml
  internal/api/admin.go
  internal/api/chat.go
  internal/api/router.go
  internal/rpc/admin/admin.go
  internal/rpc/admin/register_add_group.go
  internal/rpc/admin/user.go
  internal/rpc/chat/chat.go
  internal/rpc/chat/login.go
  internal/rpc/chat/user.go
  pkg/common/apicall/api.go
  pkg/common/apicall/caller.go
  pkg/common/apistruct/admin.go
  pkg/common/apistruct/chat.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/constant/constant.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/admin/admin.go
  pkg/common/mctx/get.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
  pkg/rpclient/openim/openim.go
  scripts/build.cmd
  scripts/start.bat
Labels: size/XL

#50 chore: Optimize project calls
  cmd/api/admin_api/main.go
  cmd/api/chat_api/main.go
  go.mod
  go.sum
  internal/api/admin.go
  internal/api/chat.go
  internal/api/router.go
  internal/rpc/admin/admin.go
  internal/rpc/admin/client_config.go
  internal/rpc/admin/invitation.go
  internal/rpc/admin/register_add_group.go
  internal/rpc/chat/chat.go
  pkg/common/apicall/api.go
  pkg/common/apicall/call.go
  pkg/common/apicall/caller.go
  pkg/common/apistruct/admin.go
  pkg/common/apistruct/chat.go
  pkg/common/config/config.go
  pkg/common/constant/constant.go
  pkg/common/db/database/admin.go
  pkg/common/db/model/admin/client_config.go
  pkg/common/db/table/admin/client_config.go
  pkg/common/mctx/get.go
  pkg/common/mw/gin_log.go
  pkg/proto/admin/admin.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/admin/api.go
  pkg/rpclient/openim/openim.go
  scripts/build_all_service.sh
  scripts/start_all.sh
Labels: size/XL

#56 fix: sql injection risk
  go.mod
  go.sum
Labels: size/XS

#58 fix searchUserInfo
  config/config.yaml
  go.mod
  go.sum
  internal/api/admin.go
  internal/api/chat.go
  internal/api/mw.go
  internal/rpc/admin/admin.go
  internal/rpc/admin/token.go
  pkg/common/apicall/caller.go
  pkg/common/config/config.go
  pkg/common/db/cache/init_redis.go
  pkg/common/db/cache/token.go
  pkg/common/db/database/admin.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/db/table/chat/attribute.go
  pkg/common/mctx/get.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/chat/chat.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/L

#59 token
  config/config.yaml
  go.mod
  go.sum
  internal/api/admin.go
  internal/api/chat.go
  internal/api/mw.go
  internal/rpc/admin/admin.go
  internal/rpc/admin/token.go
  pkg/common/apicall/caller.go
  pkg/common/config/config.go
  pkg/common/db/cache/init_redis.go
  pkg/common/db/cache/token.go
  pkg/common/db/database/admin.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/db/table/chat/attribute.go
  pkg/common/mctx/get.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/chat/chat.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/L

#61 token store
  .github/workflows/chatci.yml
  internal/api/chat.go
Labels: size/XS

#63 feat: add go relase
  .dockerignore
  .github/.codecov.yml
  .github/labels.yml
  .github/weekly-digest.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/depsreview.yaml
  .github/workflows/docker-buildx.yml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/lock-issue.yml
  .github/workflows/project-progress.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  Dockerfile
  docs/.generated_docs
  docs/CODEOWNERS
  docs/contrib/cicd-actions.md
  docs/contrib/code_conventions.md
  docs/contrib/development.md
  docs/contrib/git_workflow.md
  docs/conversions/README.md
  docs/conversions/api.md
  docs/conversions/commit.md
  docs/conversions/directory.md
  docs/conversions/error_code.md
  docs/conversions/go_code.md
  docs/conversions/images.md
  docs/conversions/logging.md
  docs/conversions/version.md
Labels: size/XXL

#64 feat: add go relase
  .dockerignore
  .github/.codecov.yml
  .github/labels.yml
  .github/weekly-digest.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/depsreview.yaml
  .github/workflows/docker-buildx.yml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/lock-issue.yml
  .github/workflows/project-progress.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  Dockerfile
  docs/.generated_docs
  docs/CODEOWNERS
  docs/contrib/cicd-actions.md
  docs/contrib/code_conventions.md
  docs/contrib/development.md
  docs/contrib/git_workflow.md
  docs/conversions/README.md
  docs/conversions/api.md
  docs/conversions/commit.md
  docs/conversions/directory.md
  docs/conversions/error_code.md
  docs/conversions/go_code.md
  docs/conversions/images.md
  docs/conversions/logging.md
  docs/conversions/version.md
Labels: size/XXL

#68 change log zerror to zinfo
  pkg/common/apicall/call.go
Labels: size/XS

#69 search Noraml User
  pkg/common/db/database/chat.go
  pkg/common/db/model/admin/forbidden_account.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/mctx/get.go
Labels: size/S

#66 bug: fix start_all.sh by merge fault
  scripts/start_all.sh
Labels: size/XS

#70 Feat/test project
  .github/workflows/build-docker-image.yml
  .github/workflows/chatci.yml
  .github/workflows/docker-buildx.yml
  .github/workflows/release.yml
  .github/workflows/scripts-test.yml
  .goreleaser.yaml
  Dockerfile
Labels: size/L

#74 fix: args check
  .goreleaser.yaml
  cmd/api/admin_api/main.go
  cmd/api/chat_api/main.go
  cmd/rpc/admin/main.go
  cmd/rpc/chat/main.go
  pkg/common/config/parse.go
  scripts/start_all.sh
Labels: size/L

#77 fix: chat config path
  config/config.yaml
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/db/cache/init_redis.go
Labels: size/M

#71 feat: test actions
  .github/workflows/build-docker-image.yml
  .github/workflows/docker-buildx.yml
  .github/workflows/release.yml
  .github/workflows/scripts-test.yml
  .github/workflows/test_2.yml
  .github/workflows/test_buildx.yml
  .goreleaser.yaml
Labels: size/L

#80 fix: args check
  .github/workflows/build-docker-image.yml
  .github/workflows/docker-buildx.yml
  .github/workflows/test_2.yml
  .github/workflows/test_buildx.yml
  .goreleaser.yaml
  Dockerfile
  cmd/api/admin_api/main.go
  cmd/api/chat_api/main.go
  cmd/rpc/admin/main.go
  cmd/rpc/chat/main.go
  config/config.yaml
  internal/rpc/chat/user.go
  pkg/common/apicall/call.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/db/cache/init_redis.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/admin/forbidden_account.go
  pkg/common/db/model/chat/attribute.go
  pkg/common/mctx/get.go
  pkg/proto/chat/chat.go
  scripts/docker_start_all.sh
  scripts/start_all.sh
Labels: size/L

#81 reset password parameter err
  pkg/proto/chat/chat.go
Labels: size/XS

#83 feat: add scripts test
  scripts/start_all.sh
Labels: size/XS

#88 fix: startup cpu usage is too high
  cmd/api/admin_api/main.go
  cmd/api/chat_api/main.go
  cmd/rpc/admin/main.go
  cmd/rpc/chat/main.go
  go.mod
  go.sum
Labels: size/M

#92 readme
  README.md
Labels: size/XS

#94 fix: startup cpu usage is too high
  cmd/api/admin_api/main.go
  cmd/api/chat_api/main.go
  cmd/rpc/admin/main.go
  cmd/rpc/chat/main.go
  go.mod
  go.sum
Labels: size/M

#93 Update README.md
  README.md
Labels: size/S

#98 fix: tools zk watch
  go.mod
  go.sum
Labels: size/XS

#97 fix: tools zk watch
  go.mod
  go.sum
Labels: size/XS

#99 fix: delete config secret
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: size/L
