Repository openimsdk/chat, pull requests merged in 2023-08, with the labels that each got.

#101 fix: docker images
  .github/workflows/build-docker-image.yml
  .github/workflows/buildx-images.yml
  .github/workflows/docker-buildx.yml
  .github/workflows/release.yml
  .github/workflows/test_buildx.yml
  .goreleaser.yaml
  Dockerfile
Labels: size/L

#102 feat: add add labels
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-tag.yml
Labels: size/M

#104 statistic api
  internal/api/admin.go
  internal/api/router.go
  internal/rpc/chat/statistic.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/register.go
  pkg/common/db/model/chat/user_login_record.go
  pkg/common/db/table/chat/register.go
  pkg/common/db/table/chat/user_login_record.go
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
  scripts/start.bat
Labels: size/L

#110 Fix the parameter error in verifying the captcha when logging in with the captcha and retrieving the password with the captcha
  internal/rpc/chat/login.go
  internal/rpc/chat/password.go
Labels: size/XS

#115 modify statistic api
  internal/api/admin.go
  internal/rpc/admin/update.go
  internal/rpc/chat/statistic.go
  pkg/common/apicall/api.go
  pkg/common/apicall/caller.go
  pkg/common/apistruct/admin.go
  pkg/common/db/database/chat.go
  pkg/common/db/model/chat/register.go
  pkg/common/db/model/chat/user_login_record.go
  pkg/common/db/table/chat/register.go
  pkg/common/db/table/chat/user_login_record.go
  pkg/proto/admin/admin.pb.go
  pkg/proto/admin/admin.proto
  pkg/proto/chat/chat.pb.go
  pkg/proto/chat/chat.proto
Labels: size/L

#113 fix: dockerfile path
  .github/workflows/build-docker-image.yml
  .github/workflows/docker-buildx.yml
  .goreleaser.yaml
  Dockerfile
  build/docker/api-admin/Dockerfile
  build/docker/api-chat/Dockerfile
  build/docker/rpc-admin/Dockerfile
  build/docker/rpc-chat/Dockerfile
  cmd/api/admin-api/Makefile
  cmd/api/admin-api/main.go
  cmd/api/chat-api/Makefile
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/Makefile
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/Makefile
  cmd/rpc/chat-rpc/main.go
  pkg/common/config/version
  scripts/admin_rpc_start.sh
  scripts/build.cmd
  scripts/build_all_service.sh
  scripts/build_docker.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/function.sh
  scripts/githooks/commit-msg
  scripts/githooks/pre-commit
  scripts/githooks/pre-push
  scripts/path_info.cfg
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/stop_all.sh
  scripts/style_info.cfg
  scripts/style_info.sh
Labels: size/XL

#120 fix: dockerfile path
  Dockerfile
  README.md
  scripts/admin_rpc_start.sh
  scripts/build_all_service.sh
  scripts/build_docker.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/function.sh
  scripts/githooks/commit-msg
  scripts/githooks/pre-commit
  scripts/githooks/pre-push
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/stop_all.sh
  scripts/style_info.sh
  test/common.sh
Labels: size/L

#121 feat: add docker fix
  scripts/docker_start_all.sh
Labels: size/XS

#124 fix: im api UserToken error non-responsive body
  internal/api/chat.go
Labels: size/XS

#125 fix: im api UserToken error non-responsive body
  internal/api/chat.go
Labels: size/XS

#122 fix: docker images version
  .github/workflows/scripts-test.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  build/docker/api-admin/Dockerfile
  build/docker/api-chat/Dockerfile
  build/docker/rpc-admin/Dockerfile
  build/docker/rpc-chat/Dockerfile
  scripts/build_all_service.sh
  scripts/start_all.sh
Labels: size/XL

#128 fix: random seed not set
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
Labels: size/S

#129 feat: add chat details
  scripts/admin_rpc_start.sh
  scripts/build_all_service.sh
  scripts/build_docker.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/function.sh
  scripts/githooks/commit-msg
  scripts/githooks/pre-commit
  scripts/githooks/pre-push
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/stop_all.sh
  scripts/style_info.sh
  test/common.sh
Labels: size/M

#130 add prompt msg
  pkg/common/db/model/admin/admin.go
Labels: size/XS

#131 chore: update version
  pkg/common/config/version
Labels: size/XS

#134 fix: script absolute path problem
  .github/dependabot.yml
  Makefile
  internal/rpc/chat/statistic.go
  scripts/check_all.sh
  scripts/path_info.sh
  scripts/stop_all.sh
Labels: size/L

#147 check_all scripts can't check if the service has started and stop_all script can't stop all service
  scripts/build_all_service.sh
  scripts/check_all.sh
  scripts/start_all.sh
  scripts/stop_all.sh
Labels: size/M

#148 start_all doesn't kill the old service
  scripts/check_all.sh
  scripts/start_all.sh
Labels: size/XS

#150 jiaoben
  scripts/start_all.sh
Labels: size/S

#152 fix: chat scripts path bug
  .github/sync.yml
  .github/workflows/sync.yml
  Dockerfile
  build/docker/api-admin/Dockerfile
  build/docker/api-chat/Dockerfile
  build/docker/rpc-admin/Dockerfile
  build/docker/rpc-chat/Dockerfile
  scripts/docker_start_all.sh
Labels: size/M

#161 config check
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  tools/component/component.go
Labels: size/L

#157 move deletelog api to admin router group
  internal/api/admin.go
  internal/api/chat.go
  internal/api/router.go
Labels: size/S

#163 login unregistered error code
  internal/rpc/chat/login.go
Labels: size/XS

#165 adjust error code range
  pkg/eerrs/predefine.go
Labels: size/S

#171 Update docker_start_all.sh
  scripts/docker_start_all.sh
Labels: size/XS

#172 feat: add openim-docker design
  config/config.yaml
  scripts/docker_start_all.sh
Labels: size/XS

#173 Update Makefile
  Makefile
Labels: size/XS

#174 feat: add test file code
  scripts/check_all.sh
  scripts/docker_start_all.sh
Labels: size/S

#175 Update check_all.sh
  scripts/check_all.sh
Labels: size/XS
