Repository openimsdk/chat, pull requests merged in 2024-10, with the labels that each got.

#584 Migration attribute data to credential
  start-config.yml
  tools/attribute-to-credential/main.go
  tools/dataversion/data_version.go
Labels: size/L

#586 fix: Update user error
  pkg/common/db/model/chat/credential.go
Labels: size/XS

#590 Fix Add User Api
  internal/api/admin/admin.go
  pkg/common/imapi/caller.go
Labels: size/M

#593 fix: search user can search email && refactor addUser
  internal/api/admin/admin.go
  pkg/common/db/model/chat/attribute.go
Labels: size/S

#595 fix: Reset password by email failed
  internal/rpc/chat/password.go
  pkg/common/db/database/chat.go
Labels: size/M

#597 fix: login check remove psw check
  internal/rpc/chat/login.go
Labels: size/XS

#600 fix: SearchFriend can search email
  pkg/common/db/model/chat/attribute.go
Labels: size/XS

#604 fix: update user email error
  internal/rpc/chat/update.go
Labels: size/XS

#608 fix: errors caused by too many tokens
  internal/api/mw/mw.go
  internal/rpc/admin/start.go
  internal/rpc/admin/token.go
  pkg/common/db/cache/token.go
  pkg/common/db/database/admin.go
  pkg/common/tokenverify/token_verify.go
Labels: size/L

#612 feat: support app update service
  internal/api/admin/admin.go
  internal/api/admin/start.go
  internal/api/chat/chat.go
  internal/api/chat/start.go
  internal/rpc/admin/application.go
  pkg/common/db/database/admin.go
  pkg/common/db/model/admin/application.go
  pkg/common/db/table/admin/application.go
  pkg/protocol/admin/admin.pb.go
  pkg/protocol/admin/admin.proto
Labels: size/L
