Repository openimsdk/chat, pull requests merged in 2024-09, with the labels that each got.

#572 fix: reset UserPassword in admin.
  internal/api/admin/admin.go
Labels: size/M

#573 refactor: improve github workflows.
  .github/.codecov.yml
  .github/code-language-detector.yml
  .github/labels.yml
  .github/sync-release.yml
  .github/weekly-digest.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-invite-comment.yml
  .github/workflows/auto-tag.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/chatci.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla-assistant.yml
  .github/workflows/cla.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-check.yml
  .github/workflows/depsreview.yaml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/issue-translator.yml
  .github/workflows/language-check.yml
  .github/workflows/project-progress.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/reopen-issue.yml
  pkg/protocol/sdkws/sdkws.proto
Labels: size/XXL

#574 feat: update RegisterUser use adminToken.
  internal/api/chat/chat.go
Labels: size/XS

#575 refactor: update token logic.
  .github/workflows/chatci.yml
  go.mod
  go.sum
  internal/api/admin/admin.go
  internal/api/chat/chat.go
  pkg/common/cmd/root.go
  pkg/common/imapi/api.go
  pkg/common/imapi/caller.go
  tools/check-component/main.go
Labels: size/M

#578 fix: mobile phone number, email address, account modification verification
  internal/rpc/chat/login.go
  internal/rpc/chat/update.go
  internal/rpc/chat/user.go
Labels: size/L

#570 fix: assign livekit node ip
  HOW_TO_SETUP_LIVEKIT_SERVER.md
  livekit/livekit.yaml
Labels: size/XS

#580 refactor: update adminToken
  go.mod
  go.sum
  internal/api/admin/admin.go
  internal/api/chat/chat.go
  pkg/common/imapi/api.go
  pkg/common/imapi/caller.go
  tools/check-component/main.go
Labels: size/M
