Repository openimsdk/chat, pull requests merged in 2024-04, with the labels that each got.

#496 fix: create RPC zookeeper node to prevent interface call blocking.
  go.mod
  go.sum
  internal/api/admin/start.go
  internal/api/chat/start.go
  pkg/common/cmd/admin_api.go
  pkg/common/cmd/admin_rpc.go
  pkg/common/cmd/chat_api.go
  pkg/common/cmd/chat_rpc.go
  pkg/common/config/config.go
Labels: size/M

#499 fix: gin log and rpc mw
  go.mod
  go.sum
  internal/api/admin/start.go
  internal/api/chat/start.go
  internal/rpc/admin/start.go
  internal/rpc/chat/start.go
Labels: size/S

#502 Optimize the Dockerfile.
  .dockerignore
  .gitignore
  Dockerfile
  go.mod
  go.sum
  start-config.yml
Labels: size/L

#508 feat: chat admin config
  config/share.yml
  internal/api/admin/start.go
  internal/api/chat/start.go
  internal/rpc/admin/start.go
  pkg/common/config/config.go
Labels: size/M

#514 Update action
  .github/workflows/chatci.yml
  .github/workflows/docker-buildx.bak
  .github/workflows/scripts-test.yml
Labels: size/M

#516 Add comments
  Dockerfile
  config/chat-api-admin.yml
  config/chat-api-chat.yml
  config/chat-rpc-admin.yml
  config/chat-rpc-chat.yml
  config/log.yml
  config/mongodb.yml
  config/redis.yml
  config/share.yml
  config/zookeeper.yml
  go.mod
  go.sum
  pkg/common/db/model/admin/ip_forbidden.go
  pkg/common/db/table/admin/admin.go
  pkg/common/db/table/admin/client_config.go
  pkg/common/db/table/admin/forbidden_account.go
  pkg/common/db/table/admin/invitation_register.go
  pkg/common/db/table/admin/ip_forbidden.go
  pkg/common/db/table/admin/limit_user_login_ip.go
  pkg/common/db/table/admin/register_add_friend.go
  pkg/common/db/table/admin/register_add_group.go
  pkg/common/db/table/chat/account.go
  pkg/common/db/table/chat/attribute.go
  pkg/common/db/table/chat/register.go
  pkg/common/db/table/chat/user_login_record.go
  pkg/common/xlsx/main.go
  pkg/common/xlsx/utils.go
  pkg/eerrs/predefine.go
  pkg/email/mail.go
Labels: size/L

#515 Add comments
  Dockerfile
  config/chat-api-admin.yml
  config/chat-api-chat.yml
  config/chat-rpc-admin.yml
  config/chat-rpc-chat.yml
  config/log.yml
  config/mongodb.yml
  config/redis.yml
  config/share.yml
  config/zookeeper.yml
  go.mod
  go.sum
  pkg/common/db/model/admin/ip_forbidden.go
  pkg/common/db/table/admin/admin.go
  pkg/common/db/table/admin/client_config.go
  pkg/common/db/table/admin/forbidden_account.go
  pkg/common/db/table/admin/invitation_register.go
  pkg/common/db/table/admin/ip_forbidden.go
  pkg/common/db/table/admin/limit_user_login_ip.go
  pkg/common/db/table/admin/register_add_friend.go
  pkg/common/db/table/admin/register_add_group.go
  pkg/common/db/table/chat/account.go
  pkg/common/db/table/chat/attribute.go
  pkg/common/db/table/chat/register.go
  pkg/common/db/table/chat/user_login_record.go
  pkg/common/xlsx/main.go
  pkg/common/xlsx/utils.go
  pkg/eerrs/predefine.go
  pkg/email/mail.go
Labels: size/L

#518 Updata action
  .github/workflows/chatci.yml
  .github/workflows/scripts-test.yml
Labels: size/M

#519 Update config.yaml
  .github/workflows/scripts-test.yml
  deployments/helm-charts/config.yaml
  pkg/protocol/admin/admin.pb.go
Labels: size/M
