Repository openimsdk/chat, pull requests merged in 2024-12, with the labels that each got.

#616 build: improve module image build and kubernetes adapt.
  .github/workflows/build-and-release-services-images.yml
  build/images/api-admin/Dockerfile
  build/images/api-chat/Dockerfile
  build/images/openim-admin-api/Dockerfile
  build/images/openim-admin-rpc/Dockerfile
  build/images/openim-chat-api/Dockerfile
  build/images/openim-chat-rpc/Dockerfile
  build/images/rpc-admin/Dockerfile
  build/images/rpc-chat/Dockerfile
  config/discovery.yml
  config/log.yml
  config/mongodb.yml
  config/share.yml
  go.mod
  go.sum
  internal/api/admin/start.go
  internal/api/chat/start.go
  internal/rpc/admin/start.go
  internal/rpc/chat/start.go
  pkg/common/cmd/admin_rpc.go
  pkg/common/cmd/chat_rpc.go
  pkg/common/cmd/root.go
  pkg/common/config/config.go
  pkg/common/config/load.go
  pkg/common/constant/constant.go
  pkg/common/kdisc/discoveryregister.go
  pkg/common/kdisc/zookeeper/doc.go
  pkg/common/kdisc/zookeeper/zookeeper.go
  pkg/common/startrpc/start.go
  tools/attribute-to-credential/main.go
  tools/check-component/main.go
  version/version
  version/version.go
Labels: size/XL

#619 feat: config center
  internal/api/admin/config_manager.go
  internal/api/admin/start.go
  internal/api/chat/start.go
  pkg/common/apistruct/config_manager.go
  pkg/common/cmd/admin_api.go
  pkg/common/cmd/admin_rpc.go
  pkg/common/cmd/chat_api.go
  pkg/common/cmd/chat_rpc.go
  pkg/common/cmd/root.go
  pkg/common/config/config.go
  pkg/common/config/env.go
  pkg/common/kdisc/etcd/config_manager.go
  pkg/common/startrpc/start.go
  tools/attribute-to-credential/main.go
  tools/check-component/main.go
Labels: size/XL

#617 build: update kubernetes deployment files.
  Dockerfile
  deployments/README.md
  deployments/deploy/chat-config.yml
  deployments/deploy/mongo-secret.yml
  deployments/deploy/openim-admin-api-deployment.yml
  deployments/deploy/openim-admin-api-service.yml
  deployments/deploy/openim-admin-rpc-deployment.yml
  deployments/deploy/openim-admin-rpc-service.yml
  deployments/deploy/openim-chat-api-deployment.yml
  deployments/deploy/openim-chat-api-service.yml
  deployments/deploy/openim-chat-rpc-deployment.yml
  deployments/deploy/openim-chat-rpc-service.yml
  deployments/deploy/redis-secret.yml
  deployments/helm-charts/.helmignore
  deployments/helm-charts/Chart.yaml
  deployments/helm-charts/charts/admin-rpc/.helmignore
  deployments/helm-charts/charts/admin-rpc/Chart.yaml
  deployments/helm-charts/charts/admin-rpc/templates/NOTES.txt
  deployments/helm-charts/charts/admin-rpc/templates/_helpers.tpl
  deployments/helm-charts/charts/admin-rpc/templates/deployment.yaml
  deployments/helm-charts/charts/admin-rpc/templates/hpa.yaml
  deployments/helm-charts/charts/admin-rpc/templates/ingress.yaml
  deployments/helm-charts/charts/admin-rpc/templates/service.yaml
  deployments/helm-charts/charts/admin-rpc/templates/serviceaccount.yaml
  deployments/helm-charts/charts/admin-rpc/values.yaml
  deployments/helm-charts/charts/chat-api/.helmignore
  deployments/helm-charts/charts/chat-api/Chart.yaml
  deployments/helm-charts/charts/chat-api/templates/NOTES.txt
  deployments/helm-charts/charts/chat-api/templates/_helpers.tpl
  deployments/helm-charts/charts/chat-api/templates/deployment.yaml
  deployments/helm-charts/charts/chat-api/templates/hpa.yaml
  deployments/helm-charts/charts/chat-api/templates/ingress.yaml
  deployments/helm-charts/charts/chat-api/templates/service.yaml
  deployments/helm-charts/charts/chat-api/templates/serviceaccount.yaml
  deployments/helm-charts/charts/chat-api/values.yaml
  deployments/helm-charts/charts/chat-rpc/.helmignore
  deployments/helm-charts/charts/chat-rpc/Chart.yaml
  deployments/helm-charts/charts/chat-rpc/templates/NOTES.txt
  deployments/helm-charts/charts/chat-rpc/templates/_helpers.tpl
  deployments/helm-charts/charts/chat-rpc/templates/deployment.yaml
  deployments/helm-charts/charts/chat-rpc/templates/hpa.yaml
  deployments/helm-charts/charts/chat-rpc/templates/ingress.yaml
  deployments/helm-charts/charts/chat-rpc/templates/service.yaml
  deployments/helm-charts/charts/chat-rpc/templates/serviceaccount.yaml
  deployments/helm-charts/charts/chat-rpc/values.yaml
  deployments/helm-charts/config.yaml
  deployments/helm-charts/templates/NOTES.txt
  deployments/helm-charts/templates/_helpers.tpl
  deployments/helm-charts/templates/app-cm.yaml
  deployments/helm-charts/templates/deployment.yaml
  deployments/helm-charts/templates/hpa.yaml
  deployments/helm-charts/templates/ingress.yaml
  deployments/helm-charts/templates/service.yaml
  deployments/helm-charts/templates/serviceaccount.yaml
  deployments/helm-charts/values.yaml
  deployments/templates/config.yaml
  go.mod
Labels: size/XXL

#620 build: fix uncorrect images.
  .github/workflows/docker-build-and-release-services-images.yml
  .github/workflows/remove-unused-labels copy.yml
Labels: size/M
