Repository openimsdk/chat, pull requests merged in 2024-11, with the labels that each got.

#613 fix: admin token cache
  internal/api/admin/admin.go
  internal/api/chat/chat.go
  pkg/common/imapi/caller.go
  pkg/common/tokenverify/token_verify.go
  tools/check-component/main.go
Labels: size/M

#609 build: implement milestone merge and update workflows.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  .github/workflows/merge-from-milestone.yml
  .github/workflows/remove-unused-labels copy.yml
  .github/workflows/remove-unused-labels.yml
  .github/workflows/update-version-file-on-release.yml
Labels: size/L

#527 fix bug:invalid go version '1.21.2' : must match format 1.23
  go.mod
Labels: size/XS
