Repository openimsdk/chat, pull requests merged in 2024-03, with the labels that each got.

#416 feat: optimize openim reset code
  .github/workflows/scripts-test.yml
  deployments/helm-charts/config.yaml
  deployments/templates/config.yaml
  scripts/admin_rpc_start.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
Labels: size/S

#417 fix: fix the component check logic to make it better
  go.mod
  go.sum
  tools/component/component.go
Labels: size/M

#420 Optimized Deployment
  .github/workflows/scripts-test.yml
  Dockerfile
  Makefile
  README.md
  scripts/admin_rpc_start.sh
  scripts/build-all-service.sh
  scripts/build_docker.sh
  scripts/check-all.sh
  scripts/check_all.sh
  scripts/docker-start-all.sh
  scripts/function.sh
  scripts/path-info.sh
  scripts/start-all.sh
  scripts/stop-all.sh
  scripts/stop_all.sh
  scripts/style-info.sh
  scripts/util.sh
Labels: size/XL

#422 fix: add graceful exit logic
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  go.mod
  go.sum
  pkg/common/chatrpcstart/start.go
  pkg/common/config/parse.go
  pkg/util/genutil.go
Labels: size/L

#425 Optimized start script for Deployment
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  deployments/templates/config.yaml
  pkg/common/config/config.go
  pkg/common/config/parse.go
  scripts/check-all.sh
  scripts/path-info.sh
  scripts/start-all.sh
  scripts/stop-all.sh
  scripts/util.sh
  tools/component/component.go
Labels: size/L

#433 fix: mongo config struct
  pkg/common/dbconn/mongo.go
Labels: size/S

#436 fix: go mod 1.19
  go.sum
Labels: size/M

#437 fix: remove duplicate character.
  scripts/start-all.sh
Labels: size/XS

#440 Update chatci.yml change go version
  .github/workflows/chatci.yml
  .github/workflows/scripts-test.yml
  go.mod
Labels: size/S

#444 update config and remove mysql conf
  deployments/templates/config.yaml
Labels: size/S

#446 fix: Crash issues caused by unconfigured MySQL
  go.sum
  pkg/common/config/parse.go
Labels: size/M

#448 Optimizing Docker-related scripts and logs
  README.md
  scripts/check-all.sh
  scripts/docker-start-all.sh
  scripts/start-all.sh
  scripts/util.sh
Labels: size/L

#450 Remove the logs directory
  scripts/check-all.sh
Labels: size/S

#452 Error:Confiquration file does notexist
  scripts/check-all.sh
  scripts/docker-start-all.sh
  scripts/start-all.sh
  scripts/util.sh
Labels: size/S

#454 Update README to add link to 'How to Setup LiveKit Server' document.
  HOW_TO_SETUP_LIVEKIT_SERVER.md
  README.md
Labels: size/M

#457 Delete .github/workflows/sync-release.yml
  .github/workflows/sync-release.yml
  .github/workflows/sync.yml
Labels: size/M

#460 fix: fix docker images
  Dockerfile
  build/images/api-admin/Dockerfile
  build/images/api-chat/Dockerfile
  build/images/rpc-admin/Dockerfile
  build/images/rpc-chat/Dockerfile
Labels: size/S

#461 docs: sora zh readme from awesome
  build/images/api-admin/Dockerfile
  build/images/api-chat/Dockerfile
  build/images/rpc-admin/Dockerfile
  build/images/rpc-chat/Dockerfile
Labels: size/XS

#462 merge main to releae-v1.6 branch
  .github/workflows/sync-release.yml
  .github/workflows/sync.yml
  Dockerfile
  HOW_TO_SETUP_LIVEKIT_SERVER.md
  README.md
  build/images/api-admin/Dockerfile
  build/images/api-chat/Dockerfile
  build/images/rpc-admin/Dockerfile
  build/images/rpc-chat/Dockerfile
Labels: size/L

#459 fix: fix the update admin info error
  internal/api/admin.go
Labels: size/XS

#470 add github actions is create code-language-detector.yml
  .github/code-language-detector.yml
  .github/workflows/language-check.yml
Labels: size/S

#467 cicd: update chat makefile fix go version minimun 1.21
  Makefile
Labels: size/XS

#477 feat: add go typecheck actions
  .github/workflows/chatci.yml
Labels: size/XS

#478 Update Makefile add test cover is 75
  Makefile
Labels: size/S
