Repository openimsdk/chat, pull requests merged in 2024-01, with the labels that each got.

#362 Update .goreleaser.yaml
  .goreleaser.yaml
Labels: size/S

#366 fix bug: read port information from the configuration file.
  scripts/check_all.sh
Labels: size/M

#367 Fix bug 365
  .goreleaser.yaml
  scripts/check_all.sh
Labels: size/M

#368 Update .gitignore add components
  .gitignore
Labels: size/XS

#370 fix: fix the go mod and fix the reset password bug
  go.mod
  go.sum
  internal/rpc/chat/chat.go
  internal/rpc/chat/password.go
  pkg/proto/chat/chat.go
Labels: size/M

#360 add gin check for resgister user info
  pkg/proto/chat/chat.go
Labels: size/XS

#374 update check_all.sh
  scripts/check_all.sh
Labels: size/S

#376 update config Readme file, add templates file
  config/Readme.md
Labels: size/XS

#375 Update README release3.4 to release3.5
  README.md
Labels: size/XS

#377 fix: del the open-util pkg
  go.mod
  go.sum
  pkg/common/tokenverify/token_verify.go
Labels: size/S

#379 feat: add a callback example that receive the message and return
  internal/api/admin.go
  internal/api/chat.go
  internal/api/router.go
  pkg/common/apistruct/chat.go
Labels: size/L

#383 fix: replace the open_utils pkg and del the unuse pkg
  go.mod
  go.sum
  pkg/common/chatrpcstart/start.go
  pkg/common/tokenverify/token_verify.go
Labels: size/S

#385 Fix(main): Ensure Database Names are Initialized in Lowercase on macOS
  deployments/templates/config.yaml
Labels: size/XS

#384 Fix(release-v1.5): Ensure Database Names are Initialized in Lowercase on macOS
  deployments/templates/config.yaml
Labels: size/XS

#386 feat: supoort openim-chat source code deployment in mac
  README.md
  scripts/check_all.sh
  scripts/path_info.sh
  scripts/start_all.sh
Labels: size/L

#390 Update check_all.sh
  scripts/check_all.sh
Labels: size/XS

#387 fix: wrap the errors
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  internal/rpc/admin/admin.go
  internal/rpc/chat/chat.go
  pkg/common/chatrpcstart/start.go
  pkg/common/config/parse.go
  pkg/email/mail.go
  pkg/email/mail_test.go
Labels: size/M

#393 update check_all.sh fix mac check scripts
  scripts/check_all.sh
Labels: size/XS

#397 Standardizing Log Path: Migrating chat Service Startup Logs to _output/logs
  .github/workflows/scripts-test.yml
  scripts/admin_rpc_start.sh
  scripts/build_all_service.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/start_all.sh
Labels: size/S

#395 fix: Refactoring callbackexample
  example/callback/callback.go
  internal/api/chat.go
  internal/api/router.go
Labels: size/XL

#400 bug(main): update check_all fix chat scripts logs print
  scripts/check_all.sh
Labels: size/XS

#401 feat: del the AdminList configure and it's init statement
  deployments/templates/config.yaml
  pkg/common/config/parse.go
  pkg/common/db/model/admin/admin.go
  pkg/common/mctx/get.go
Labels: size/M

#403 fix(release-v1.5): fix release-v1.5 scritps bug support mac deployment
  scripts/admin_rpc_start.sh
  scripts/build_all_service.sh
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/path_info.sh
  scripts/start_all.sh
Labels: size/L

#404 fix: replace the component check func by tools pkg
  cmd/api/admin-api/main.go
  cmd/api/chat-api/main.go
  cmd/rpc/admin-rpc/main.go
  cmd/rpc/chat-rpc/main.go
  go.mod
  go.sum
  pkg/common/config/parse.go
  tools/component/component.go
Labels: size/L
