Repository openimsdk/chat, pull requests merged in 2025-01, with the labels that each got.

#621 feat: Add enable config center button && fix: grpc connection leakage
  go.mod
  go.sum
  internal/api/admin/admin.go
  internal/api/admin/config_manager.go
  internal/api/admin/start.go
  internal/api/chat/chat.go
  internal/api/chat/start.go
  pkg/common/apistruct/config_manager.go
  pkg/common/cmd/admin_rpc.go
  pkg/common/cmd/chat_rpc.go
  pkg/common/cmd/root.go
  pkg/common/kdisc/discoveryregister.go
  pkg/common/kdisc/etcd/config_manager.go
  pkg/common/kdisc/etcd/const.go
  pkg/common/startrpc/start.go
Labels: size/L

#623 fix: Error will print stack
  go.mod
  go.sum
Labels: size/XS

#626 fix: update protoc gen && gen proto
  go.mod
  go.sum
  internal/rpc/admin/start.go
  internal/rpc/chat/start.go
  pkg/protocol/admin/admin.pb.go
  pkg/protocol/admin/admin.proto
  pkg/protocol/admin/admin_grpc.pb.go
  pkg/protocol/chat/chat.pb.go
  pkg/protocol/chat/chat_grpc.pb.go
  pkg/protocol/common/common.pb.go
  pkg/protocol/common/common.proto
  pkg/protocol/gen.cmd
  pkg/protocol/gen.sh
  pkg/protocol/sdkws/sdkws.proto
  pkg/protocol/wrapperspb/wrapperspb.proto
Labels: size/L

#627 build: update chat CI test.
  .github/workflows/build-docker-image.yml
  .github/workflows/changelog.yml
  .github/workflows/chat-build-test.yml
  .github/workflows/chatci.yml
  .github/workflows/docker-build-and-release-services-images.yml
  .github/workflows/merge-from-milestone.yml
  Dockerfile
Labels: size/XL

#629 build: improve workflows and docker contents.
  .github/workflows/build-docker-image.yml
  .github/workflows/changelog.yml
  .github/workflows/chat-build-test.yml
  .github/workflows/chatci.yml
  .github/workflows/docker-build-and-release-services-images.yml
  .github/workflows/merge-from-milestone.yml
  Dockerfile
Labels: size/XL
